### ISSUE TITLE
Data validation 

### ISSUE THREAD

**Issue by DmitriyShalaev** [crypto-trading-solutions/rwi_strategy#1]
Validate data from adapter as :
_{
  "Ticker": "ETHUSDT",
  "Price": "243.03",
  "Time": "2020-06-08T16:54:00Z",
  "Strategy": "rwi",   
  "Action": "long"
 }_
And serialize as **js** object.

**Comment by DmitriyShalaev** [comment]
https://github.com/crypto-trading-solutions/rwi_strategy/tree/issue_1

**Comment by sankyago** [comment]
```
{
    "availableStrategy": "rwi",
    "availableActions": [
        "long",
        "short"
    ],
    "errors": {},
    "ticker": "ETHUSD",
    "price": 250,
    "time": "2020-06-08T16:54:00Z",
    "strategy": "rwi",
    "action": "long"
}
```

**Comment by DmitriyShalaev** [comment]
https://github.com/crypto-trading-solutions/rwi_strategy/pull/4
