### ISSUE TITLE
binance api js layer 

### ISSUE THREAD

**Issue by DmitriyShalaev** [crypto-trading-solutions/rwi_strategy#5]
Adapt Binance API calls to js methods.

**REQUIREMENTS**:
Execute Methods using "API Authentication" objects as a parameter.

**API Authentication object**:

- API_PUBLIC_KEY

- API_SECRET_KEY

**USED METHODS**:

- [x] 1. Get balance:        (auth_obj)

- [x] Check route

- [x] 2. Open limit order  (auth_obj,symbol,price,amount)

- [x] Check route

- [x] 3. List open orders (auth_obj)

- [x] Check route

- [x] 4. List open positions (auth_obj)

- [x] Check route

- [x] 5. Close position (auth_obj,symbol,price)

- [x] Check route

- [x] 6. Cancel order (auth_obj,order_id)

- [x] Check route

- [x] 7. FuturesOpenOrders(auth_obj,symbol)

- [x] Check route

- [x] 8. SpotOpenOrders(auth_obj,symbol)

- [x] Check route

- [x] 9. FuturesExchangeInfo(auth_obj,symbol)

- [x] Check route

- [x] 10. Change Position Mode

- [x] Check route

**Comment by sankyago** [comment]
_const reqHandler = cb => ( error, response, body ) => {
        Binance.info.lastRequest = new Date().getTime();
        Binance.info.lastURL = response.request.uri.href;
        Binance.info.statusCode = response.statusCode;
        Binance.info.usedWeight = response.headers['x-mbx-used-weight-1m'] || 0;
        Binance.info.orderCount1s = response.headers['x-mbx-order-count-1s'] || 0;
        Binance.info.orderCount1m = response.headers['x-mbx-order-count-1m'] || 0;
        Binance.info.orderCount1h = response.headers['x-mbx-order-count-1h'] || 0;
        Binance.info.orderCount1d = response.headers['x-mbx-order-count-1d'] || 0;
        if ( !cb ) return;
        if ( error ) return cb( error, {} );
        if ( response && response.statusCode !== 200 ) return cb( response, {} );
        return cb( null, JSON.parse( body ) );
    }_

**Comment by sankyago** [comment]
Done
